language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - if [ -d ./vendor ]; then rm -rf vendor && rm composer.lock; fi
    - composer install

script: ./run-tests

notifications:
    email:
        recipients:
            - elias.alves.chacon@gmail.com
        on_success: [always|never|change] # default: change
        on_failure: [always|never|change] # default: always

